import { jsxs as _jsxs, jsx as _jsx } from "react/jsx-runtime";
import { ContextHelpButton } from '../ContextHelpButton';
import { ProjectContainer, ProjectHeader, ProjectName, ProjectDescription, StatsGrid, StatCard, StatLabel, StatValue, InterfacesHeading, InterfacesList, InterfaceItem, InterfaceInfo, InterfaceName, InterfaceOps, InterfaceDef, ChevronIcon } from '../../styles/WorkspaceLayout.styles';
export const ProjectSummary = ({ project, onSelectInterface }) => {
    // Calculate statistics
    const totalOperations = project.interfaces.reduce((sum, iface) => sum + iface.operations.length, 0);
    const totalRequests = project.interfaces.reduce((sum, iface) => sum + iface.operations.reduce((opSum, op) => opSum + op.requests.length, 0), 0);
    return (_jsxs(ProjectContainer, { children: [_jsxs(ProjectHeader, { children: [_jsxs("div", { children: [_jsxs(ProjectName, { children: ["Project: ", project.name] }), project.description && _jsx(ProjectDescription, { children: project.description })] }), _jsx(ContextHelpButton, { sectionId: "workspace" })] }), _jsxs(StatsGrid, { children: [_jsxs(StatCard, { children: [_jsx(StatLabel, { children: "Interfaces" }), _jsx(StatValue, { children: project.interfaces.length })] }), _jsxs(StatCard, { children: [_jsx(StatLabel, { children: "Test Suites" }), _jsx(StatValue, { children: project.testSuites?.length || 0 })] }), _jsxs(StatCard, { children: [_jsx(StatLabel, { children: "Operations" }), _jsx(StatValue, { children: totalOperations })] }), _jsxs(StatCard, { children: [_jsx(StatLabel, { children: "Requests" }), _jsx(StatValue, { children: totalRequests })] })] }), _jsx(InterfacesHeading, { children: "Interfaces" }), _jsx(InterfacesList, { children: project.interfaces.map(iface => (_jsxs(InterfaceItem, { onClick: () => onSelectInterface && onSelectInterface(iface), children: [_jsxs(InterfaceInfo, { children: [_jsx(InterfaceName, { children: iface.name }), _jsxs(InterfaceOps, { children: [iface.operations.length, " operations"] }), iface.definition && (_jsx(InterfaceDef, { children: iface.definition }))] }), _jsx(ChevronIcon, { size: 16 })] }, iface.name))) })] }));
};
